# Build mongo-c-driver on latest Windows using available Visual Studio Versions.

name: Build mongo-c-driver

on:
    push:
        branches: [ main ]

    workflow_dispatch:

jobs:
  
  mongo-c-driver:
    runs-on: windows-latest

    strategy:
      matrix: 
        mongoversion: ['1.16.2', '1.20.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create new release branch or checkout and pull the release branch
      run: |
        git config --global user.name 'crazyzlj'
        git config --global user.email 'crazyzlj@gmail.com'
        if (git ls-remote --exit-code --heads origin release) { 
          Write-Host "Branch release exists, pull it."
          git pull
          git checkout -b release origin/release
          Remove-Item ".github" -recurse -force
          git add .
          git commit -m "remove old code"
          git merge --no-ff -m "merge changes of main branch" main --allow-unrelated-histories
        } else {
          Write-Host "Branch release not exist, checkout for a new branch."
          git checkout -b release
        }

    - name: Build mongo-c-driver
      run: ${{github.workspace}}\.github\workflows\build_mongo-c-driver.ps1 -buildPath ${{github.workspace}}\build-${{ matrix.mongoversion }} -mongoVersion ${{ matrix.mongoversion }} -installPath ${{github.workspace}}\releases

    - name: Commit built library
      run: |
        git add .
        git commit -am "Build mongo-c-driver on Windows"
        if (git ls-remote --exit-code --heads origin release) {
          git pull origin release
        }
        git push origin release
